### PR TITLE
Remove get_prns_from_constellation

### PR DESCRIPTION
**Pull request by fivitti**
Hi!
I refactor your code to abandon "get_prns_from_constellation" function. My intention was to protect the code from fail after launch next satellites.

1. I remove constants with constellation sizes
2. I refactor offsets to use values from [NMEA Revealed](https://gpsd.gitlab.io/gpsd/NMEA.html)
    I noticed that you used 96 as offset for Galileo. Sources from Internet say that Galileo offset start from 301, but it is unofficial information. I set value equals 301 in code, but if you have any information about real Galileo offset then I can change offset.
   
    I cannot completely remove these constants, because RINEX parser uses it, but AstroDog is now independent of that. I added new method "get_all_sat_info" for return sat info from all fetched ephemeris. It covers the use case when get_prns_from_constellation was used,
3. I remove "bad_sats" list. I noticed then if you first try fetch data for date missing (for example for 2000 year for C01) then it is put on the bad list and if you try again fetch data for date when data exists (for example 2020) then you get None. I refactor it and I add unit test to check this case.
4. I fix bug with fetch RINEX data from 2000 year.

BTW I have few remarks. If you want I can add them as issues:
1. If no  ephemeris are fetched then Laika throws RuntimeException. It is confused for me, because in other cases if AstroDog doesn't found sat info then it returns None.
2. If pull_orbit is set to False then Laika fetch sat info only for GPS and GLONASS. But user doesn't have any information that it fails for other constellations. Maybe any not supported exception when you want create Laika object?

Related to #21 .

### CODE REVIEW

**Comment by fivitti** [comment]
Maybe "get_prn_from_nmea_id" should return PRN for unknown constellations with special symbol instead of raise NotImplementedException?

For example: ```get_prn_from_nmea_id(1000)``` raises now NotImplementedException. But maybe it should count all empty NMEA ranges and return PRN with "?" symbol as constellation: ```get_prn_from_nmea_id(1000) == "?345".

I noticed that when I execute "test_station_position" from "test_positioning.py" then in 39 line I got  GPS and GLONASS satellites and one unknown object with 132 NMEA ID. Now it gets "S45" PRN.
But if RINEX may to contains unknown NMEA ID then it may fail if NMEA ID will be from unknown range. If we implement unknown symbol then it will be work forever.

**Comment by fivitti** [comment]
And maybe "get_constellation " should return None when constellation is unknown instead of raise exception? What do you think? When orbit data doesn't found in AstroDog then Laika returns None.

**Comment by HaraldSchafer** [comment]
Yes, please add your 2 remarks as issues. Those should ideally be fixed.

**Comment by HaraldSchafer** [comment]
I think it makes sense for get_prn_from_nmea_id to raise an error if the constellation is unknown. Since if it's not known whatever uses it's output would likely break.

**Comment by HaraldSchafer** [comment]
And maybe of get_constellation gets an unknown constellation we can raise a warning and return None?

**Comment by HaraldSchafer** [comment]
Pull request looks great btw! I only have one concern, without bad sats, I'm worried that it will keep retrying to get data when it has already failed. Not sure if this can be an issue.

**Comment by fivitti** [comment]
> Ok, I do it ASAP
Yes, please add your 2 remarks as issues. Those should ideally be fixed.

> I think it makes sense for get_prn_from_nmea_id to raise an error if the constellation is unknown. Since if it's not known whatever uses it's output would likely break.

It depends. If RINEX files may to contains unexpected NMEA ID (as I described above) then throw Laika shouldn't raise Exception, because developer cannot handle it (cannot fix downloaded RINEX file). And rest of parsed message is correct and may be used. Maybe satellites from unknown constellation should be skipped? But I think that user of this library should decide.

> And maybe of get_constellation gets an unknown constellation we can raise a warning and return None?
It makes sense for me. Do you wan't a raise warning as any special object or only print on console?

> Pull request looks great btw! I only have one concern, without bad sats, I'm worried that it will keep retrying to get data when it has already failed. Not sure if this can be an issue.
But if you want in the same program first fetch data for all available satellites from old year and next from now then some satellites will be not fetch.
For example developer (and end user) probably don't know when first GLONASS or BEIDOU satellite was launch and since when orbit data are available. If it provides incorrect data (before launch) then first it has any message that in next fetch this satellite will be ignored and second it must manually to clear bad satellite list and it must know which exactly remove.

**Comment by HaraldSchafer** [comment]
> It depends. If RINEX files may to contains unexpected NMEA ID (as I described above) then throw Laika shouldn't raise Exception, because developer cannot handle it (cannot fix downloaded RINEX file). And rest of parsed message is correct and may be used. Maybe satellites from unknown constellation should be skipped? But I think that user of this library should decide.
 
Yes you are right. Let's just do a warning and return None then.

> It makes sense for me. Do you want to raise warning as any special object or only print on console?

I think python warnings make sense here 
https://docs.python.org/3/library/warnings.html


> But if you want in the same program first fetch data for all available satellites from old year and next from now then some satellites will be not fetch.
> For example developer (and end user) probably don't know when first GLONASS or BEIDOU satellite was launch and since when orbit data are available. If it provides incorrect data (before launch) then first it has any message that in next fetch this satellite will be ignored and second it must manually to clear bad satellite list and it must know which exactly remove.

Yes, that is a problem. I've never used an AstroDog object for long time periods like that, so never experienced this issue. But it should be fixed. We can't just remove that logic though. Without bad_sats if you have a GNSS data with a lot of measurements from satellite R07 for example, and AstroDog cannot find data for it then it will just keep trying to find data. I think the correct approach is to add some kind of InvalidEphemeris object or something like it. That also has a time window. And that as long as that invalid object is inside the time window it returns None. I added a test to CI that tests this. If you rebase your PR on master it should fail.

**Comment by fivitti** [comment]
> Yes you are right. Let's just do a warning and return None then.

I cannot returns None as PRN. A lot of functions take that PRN is str. It isn't used in any processing, but it is a member of structures. I think also that NMEA ID may be useful as fallback when Laika cannot create a valid PRN.

I propose convention that when NMEA ID cannot be convert transform into PRN then Laika return string which starts with quote mark "?" and next is NMEA ID. For example for NMEA ID equals 160 you get "?160".

I implement it in ```get_prn_from_nmea_id``` and ```get_nmea_id_from_prn``` functions. I add also util functions: ```get_unknown_prn_from_nmea_id```, ```get_nmea_id_from_unknown_prn``` and ```is_unknown_prn``` to support it, but I don't need to use it in Laika code.

Function ```get_constellation``` now returns None for any unknown constellations (also for "?"). It raises also warning.

> Yes, that is a problem. I've never used an AstroDog object for long time periods like that, so never experienced this issue. But it should be fixed. We can't just remove that logic though. Without bad_sats if you have a GNSS data with a lot of measurements from satellite R07 for example, and AstroDog cannot find data for it then it will just keep trying to find data. I think the correct approach is to add some kind of EphemerisNotFound object or something like it. That also has a time window. And if you make requests in that time window it returns None. I added a test to CI that tests this. If you rebase your PR on master it should fail.

It wasn't easy task. :)

First I implemented solution suggested by you - based on EphemerisNotFound. When no data found for specific PRN then I insert EphemerisNotFound object with epoch and PRN and ```valid``` method to ```orbits```, ```decbs``` or ```nav``` dictionaries. I can mark with it only one PRN, but I need to mark many PRNs as no data (all not fetched). I cannot do it, because I remove PRN list.

Commited solution uses special data structure for remember which dates are fetched - ```TimeRangeHolder```. You can insert date range to it and test if date is in any range already added.

```python
start_time = GPSTime.from_datetime(datetime(2020, 4, 28))
end_time = GPSTime.from_datetime(datetime(2020, 5, 2))
time = GPSTime.from_datetime(datetime(2020, 5, 1))

holder = TimeRangeHolder()
holder.add(start_time, end_time)

self.assertTrue(time in holder)
```

It store only union of added ranges then it shouldn't use a lot of memory. It is also optimized for checking then it should be fast. It pass your test of course.

After each download ephemeris Laika search for minimum and maximum epoch, next add min time diff interval suitable for specific ephemeris and add this range into TimeRangeHolder.

```python
if len(ephems_sp3) != 0:
    min_ephem = min(ephems_sp3, key=lambda e: e.epoch)
    max_ephem = max(ephems_sp3, key=lambda e: e.epoch)

    min_epoch = min_ephem.epoch - min_ephem.max_time_diff
    max_epoch = max_ephem.epoch + max_ephem.max_time_diff

    self.orbit_fetched_times.add(min_epoch, max_epoch)
```

Next when user call Laika for this data holder is tested and if no data found and Laika already fetched data for specific time then None is returned.

```python
def get_orbit(self, prn, time):
    if self.cached_orbit[prn] is not None and self.cached_orbit[prn].valid(time):
      return self.cached_orbit[prn]

    self.cached_orbit[prn] = get_closest(time, self.orbits[prn])
    if self.cached_orbit[prn] is not None and self.cached_orbit[prn].valid(time):
      return self.cached_orbit[prn]

    # Already fetched, but no data found
    if time in self.orbit_fetched_times:
      return None

    self.get_orbit_data(time)
    self.cached_orbit[prn] = get_closest(time, self.orbits[prn])
    if self.cached_orbit[prn] is not None and self.cached_orbit[prn].valid(time):
      return self.cached_orbit[prn]
    else:
      return None
```

I can't wait for your feedback!

**Comment by HaraldSchafer** [comment]
>I cannot returns None as PRN. A lot of functions take that PRN is str. It isn't used in any processing, but it is a member of structures. I think also that NMEA ID may be useful as fallback when Laika cannot create a valid PRN.

>I propose convention that when NMEA ID cannot be convert transform into PRN then Laika return string which starts with quote mark "?" and next is NMEA ID. For example for NMEA ID equals 160 you get "?160".

>I implement it in get_prn_from_nmea_id and get_nmea_id_from_prn functions. I add also util functions: get_unknown_prn_from_nmea_id, get_nmea_id_from_unknown_prn and is_unknown_prn to support it, but I don't need to use it in Laika code.

Sounds good!

>First I implemented solution suggested by you - based on EphemerisNotFound. When no data found for specific PRN then I insert EphemerisNotFound object with epoch and PRN and valid method to orbits, decbs or nav dictionaries. I can mark with it only one PRN, but I need to mark many PRNs as no data (all not fetched). I cannot do it, because I remove PRN list.

Sweet! This provides the needed functionality. 

This does make the assumption that the function `get_orbit_data` and others, must pull data for all constellations supported by that AstroDog object, not just the constellation you are currently requesting data for. But I think that is a fair assumption.

**Pull request merged**
