### PR TITLE
* 修复curl密钥问题导致下载失败的bug

### PR DESCRIPTION
**Pull request by mengyou658**

### CODE REVIEW

**Comment by HaraldSchafer** [comment]
What does this fix?

**Comment by mengyou658** [comment]
@HaraldSchafer

**Comment by HaraldSchafer** [comment]
Ah for windows, I see. Well the github tests fail. If you make them pass I can merge :)

**Comment by mengyou658** [comment]
@HaraldSchafer  its the lint error, i fixed

**Pull request merged**
